// src/main/web/dashboard/dependencies.jsx
import { useState } from 'react';
import './icons.css';

const Dependencies = ({ dependencies }) => {
  const [sortByDep, setSortByDep] = useState('status');
  const [sortDirectionDep, setSortDirectionDep] = useState('desc');

  const columns = dependencies.length > 0 ? Object.keys(dependencies[0]) : [];

  const sortedDependencies = [...dependencies].sort((a, b) => {
    const modifier = sortDirectionDep === 'desc' ? -1 : 1;
    if (a[sortByDep] < b[sortByDep]) return -1 * modifier;
    if (a[sortByDep] > b[sortByDep]) return modifier;
    return 0;
  });

  const sort = (param) => {
    if (param === sortByDep) {
      setSortDirectionDep(sortDirectionDep === 'asc' ? 'desc' : 'asc');
    }
    setSortByDep(param);
  };

  return (
    <div className="boxed-group boxed-group-inner">
      <h3>Dependencies</h3>
      <table className="data zebra">
        <caption>
          Here you see all project dependencies from Maven (including transitive) and NPM.
        </caption>
        <thead>
          <tr>
            {columns.map((dependency) => (
              <th key={dependency} onClick={() => sort(dependency)} scope="col">
                {dependency}
                {dependency === sortByDep && (
                  <div className={`arrow ${sortDirectionDep === 'asc' ? 'arrow_up' : 'arrow_down'}`} />
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sortedDependencies.map((dependency) => (
            <tr key={dependency.name}>
              <td>{dependency.name}</td>
              <td>{dependency.version}</td>
              <td>{dependency.license}</td>
              <td>
                <span className={
                  dependency.status === 'Allowed' ? 'icon-license-ok' :
                  dependency.status === 'Forbidden' ? 'icon-license-nok' :
                  'icon-license-unknown'
                } />
                {dependency.status}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Dependencies;

// src/main/web/dashboard/dependencies.vue
<template>
  <div class="boxed-group boxed-group-inner">
    <h3>Dependencies</h3>
    <table class="data zebra">
      <caption>Here you see all project dependencies from Maven (including transitive) and NPM.</caption>
      <thead>
        <tr>
          <th v-for="dependency in columns" v-bind:key="dependency" v-on:click="sort(dependency)" scope="col"> {{dependency}} 
            <div class="arrow" v-if="dependency == sortByDep" v-bind:class="{ 'arrow_up' : sortDirectionDep === 'asc', 'arrow_down' : sortDirectionDep === 'desc'}"></div>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(dependency) in sortedDependencies" v-bind:key="dependency.name">
          <td>{{dependency.name}}</td>
          <td>{{dependency.version}}</td>
          <td>{{dependency.license}}</td>
          <td>
            <span
              :class="{ 'icon-license-ok': dependency.status === 'Allowed', 'icon-license-nok': dependency.status === 'Forbidden', 'icon-license-unknown': dependency.status === 'Unknown' }"
            ></span>
            {{dependency.status}}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

  <script>
export default {
  props: ["dependencies"],
  data() {
    return {
      dependency: {
        name: "",
        version: "",
        license: "",
        status: ""
      },
      sortByDep: "status",
      sortDirectionDep: "desc"
    };
  },
  computed: {
    sortedDependencies() {
      return this.dependencies.sort((a, b) => {
        let modifier = 1;
        if (this.sortDirectionDep === "desc") modifier = -1;
        if (a[this.sortByDep] < b[this.sortByDep]) return -1 * modifier;
        if (a[this.sortByDep] > b[this.sortByDep]) return 1 * modifier;
        return 0;
      });
    },
    "columns": function columns() {
      if (this.dependencies.length == 0) {
        return [];
      }
      return Object.keys(this.dependencies[0])
    }
  },
  methods: {
    sort(param) {
      if (param === this.sortByDep) {
        this.sortDirectionDep = this.sortDirectionDep === "asc" ? "desc" : "asc";
      }
      this.sortByDep = param;
    }
  }
};
</script>

<style>
@import "icons.css";
</style>
