// src/main/web/dashboard/licenses.jsx
import { useState } from "react";
import "./icons.css";

const Licenses = ({ licenses }) => {
  const [sortBy, setSortBy] = useState("status");
  const [sortDirection, setSortDirection] = useState("asc");

  const columns = licenses.length > 0 ? Object.keys(licenses[0]) : [];

  const sortedLicenses = [...licenses].sort((a, b) => {
    const modifier = sortDirection === "desc" ? -1 : 1;
    if (a[sortBy] < b[sortBy]) return -1 * modifier;
    if (a[sortBy] > b[sortBy]) return 1 * modifier;
    return 0;
  });

  const sort = (param) => {
    if (param === sortBy) {
      setSortDirection(sortDirection === "asc" ? "desc" : "asc");
    }
    setSortBy(param);
  };

  return (
    <div className="boxed-group boxed-group-inner">
      <h3>Licenses</h3>
      <table className="data zebra">
        <caption>This is a list of all licenses used in any dependencies listed below.</caption>
        <thead>
          <tr>
            {columns.map((license) => (
              <th key={license} onClick={() => sort(license)} scope="col">
                {license}
                {license === sortBy && (
                  <div className={`arrow ${sortDirection === "asc" ? "arrow_up" : "arrow_down"}`} />
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sortedLicenses.map((license) => (
            <tr key={license.identifier}>
              <td>{license.identifier}</td>
              <td>{license.name}</td>
              <td>
                <span
                  className={`${license.status === "true" ? "icon-license-ok" : "icon-license-nok"}`}
                />
                {license.status === "true" ? "Allowed" : "Forbidden"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Licenses;

// src/main/web/dashboard/licenses.vue
<template>
  <div class="boxed-group boxed-group-inner">
    <h3>Licenses</h3>
    <table class="data zebra">
      <caption>This is a list of all licenses used in any dependencies listed below.</caption>
      <thead>
        <tr>
          <th v-for="license in columns" v-bind:key="license" v-on:click="sort(license)" scope="col"> {{license}} 
            <div class="arrow" v-if="license == sortBy" v-bind:class="{ 'arrow_up' : sortDirection === 'asc', 'arrow_down' : sortDirection === 'desc'}"></div>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(license) in sortedLicenses" v-bind:key="license">
          <td>{{license.identifier}}</td>
          <td>{{license.name}}</td>
          <td>
            <span :class="{ 'icon-license-ok': license.status === 'true', 'icon-license-nok': license.status !== 'true' }"></span>
            {{ license.status === 'true' ? 'Allowed' : 'Forbidden' }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>


</template>

<script>
  export default {
props: ["licenses"],
  data() {
    return {
      license: {
        identifier: "",
        name: "",
        status: ""
      },
      sortBy: 'status',
      sortDirection: 'asc'
    };
  },
  computed: {
    sortedLicenses() {
      return this.licenses.sort((a, b) => {
        let modifier = 1;
        if (this.sortDirection === 'desc') modifier = -1;
        if (a[this.sortBy] < b[this.sortBy]) return -1 * modifier;
        if (a[this.sortBy] > b[this.sortBy]) return 1 * modifier;
        return 0;
      });
    },
    "columns": function columns() {
      if (this.licenses.length == 0) {
        return [];
      }
      return Object.keys(this.licenses[0])
    }
  },
  methods: {
    sort(param) {
      if (param === this.sortBy) {
        this.sortDirection = this.sortDirection === "asc" ? "desc" : "asc";
      }
      this.sortBy = param;
    }
  }
};
</script>

<style>
  @import "icons.css";
</style>
