// src/main/web/modal-dialog.jsx
import { useEffect } from 'react';

const ModalDialog = ({ header, show, onClose, children, footer }) => {
  useEffect(() => {
    const handleEscape = (e) => {
      if (show && e.keyCode === 27) {
        onClose();
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [show, onClose]);

  if (!show) return null;

  return (
    <>
      <div className="modal in">
        <div className="modal-head">
          <h2>{header}</h2>
        </div>
        <div className="modal-body">
          {children}
        </div>
        <div className="modal-foot">
          {footer}
          <a href="#" className="button button-link" onClick={onClose}>Cancel</a>
        </div>
      </div>
      <div className="modal-overlay in"></div>
    </>
  );
};

export default ModalDialog;

// src/main/web/modal-dialog.vue
<template>
  <div v-if="show">
    <div class="modal in">
      <div class="modal-head">
        <h2>{{header}}</h2>
      </div>
      <div class="modal-body">
        <slot name="body"></slot>
      </div>
      <div class="modal-foot">
        <slot name="footer"></slot>
        <a href="#" class="button button-link" @click="close()">Cancel</a>
      </div>
    </div>
    <div class="modal-overlay in"></div>
  </div>
</template>

<script>
export default {
  props: {
    header: String,
    show: Boolean
  },
  methods: {
    close() {
      this.$emit('close');
    }
  },
  mounted() {
    document.addEventListener('keydown', (e) => {
      if (this.show && e.keyCode == 27) {
        this.close();
      }
    });
  }
};
</script>
